export const SYSTEM_CONFIG_KEYS = {
  SUPPORTED_AREA_NAME: 'SUPPORTED_AREA_NAME',
  SUPPORTED_PROVINCE_CODES: 'SUPPORTED_PROVINCE_CODES',
  SUPPORTED_AREA_KEYWORDS: 'SUPPORTED_AREA_KEYWORDS',

  TOPUP_VND_PER_USD: 'TOPUP_VND_PER_USD',
  TOPUP_MIN_VND: 'TOPUP_MIN_VND',
  TOPUP_MAX_VND: 'TOPUP_MAX_VND',

  WITHDRAWAL_MIN_VND: 'WITHDRAWAL_MIN_VND',
  WITHDRAWAL_MAX_VND: 'WITHDRAWAL_MAX_VND',
  WITHDRAWAL_MAX_PER_WEEK: 'WITHDRAWAL_MAX_PER_WEEK',

  PLATFORM_COMMISSION_RATE_PERCENT: 'PLATFORM_COMMISSION_RATE_PERCENT',

  TASKER_MIN_ACCEPT_BALANCE_VND: 'TASKER_MIN_ACCEPT_BALANCE_VND',

  DISPATCH_URGENT_RADIUS_METERS: 'DISPATCH_URGENT_RADIUS_METERS',
  DISPATCH_NORMAL_RADIUS_METERS: 'DISPATCH_NORMAL_RADIUS_METERS',
  DISPATCH_URGENCY_THRESHOLD_MINUTES: 'DISPATCH_URGENCY_THRESHOLD_MINUTES',

  PREMIUM_FAVORITE_WAIT_SECONDS: 'PREMIUM_FAVORITE_WAIT_SECONDS',
} as const;

export type SystemConfigKey =
  (typeof SYSTEM_CONFIG_KEYS)[keyof typeof SYSTEM_CONFIG_KEYS];
