export const SYSTEM_CONFIG_KEYS = {
  SUPPORTED_AREA_NAME: 'SUPPORTED_AREA_NAME',
  SUPPORTED_PROVINCE_CODES: 'SUPPORTED_PROVINCE_CODES',
  SUPPORTED_AREA_KEYWORDS: 'SUPPORTED_AREA_KEYWORDS',
} as const;
