export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    REFRESH: "/auth/refresh",
    ME: "/auth/me",
    PROFILE: "/auth/profile",
    LOGOUT: "/auth/logout",
    VERIFY_EMAIL: "/auth/verify-email",
    RESEND_VERIFICATION_EMAIL: "/auth/resend-verification-email",
    VERIFY_LOGIN_OTP: "/auth/verify-login-otp",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
  },
  USERS: {
    BASE: "/users",
    PROFILE: "/users/profile",
  },
  CUSTOMER: {
    ADDRESSES: "/customer/addresses",
    ADDRESS: (id: string) => `/customer/addresses/${id}`,
    DEFAULT_ADDRESS: (id: string) => `/customer/addresses/${id}/default`,
  },
  TASKERS: {
    BASE: "/taskers",
    VERIFY: "/taskers/verify",
  },
  SERVICES: {
    BASE: "/services",
    CATEGORIES: "/services/categories",
  },
  BOOKING: {
    // Customer APIs
    QUOTE: "/booking/quote",
    CREATE: "/booking",
    MY_ACTIVE: "/booking/my-booking",
    DETAIL: (id: string) => `/booking/${id}`,
    CANCEL: (id: string) => `/booking/customer/${id}/cancel`,
    UPDATE_SCHEDULE: (id: string) => `/booking/${id}/schedule-address`,
    // Tasker APIs
    TASKER_POSTED_LIST: "/booking/tasker/posted",
    TASKER_POSTED_DETAIL: (id: string) => `/booking/tasker/posted/${id}`,
    TASKER_ACCEPT: (id: string) => `/booking/tasker/posted/${id}/accept`,
    TASKER_ASSIGNED: (id: string) => `/booking/tasker/${id}`,
    TASKER_ON_WAY: (id: string) => `/booking/tasker/${id}/on-the-way`,
    TASKER_CHECKIN: (id: string) => `/booking/tasker/${id}/check-in`,
    TASKER_START: (id: string) => `/booking/tasker/${id}/start`,
    TASKER_COMPLETE: (id: string) => `/booking/tasker/${id}/complete`,
  },
  ADMIN_SUPPORT_TICKETS: {
    BASE: "/admin/support-tickets",
    CONFIG: "/admin/support-tickets/config",
    DETAIL: (id: string) => `/admin/support-tickets/${id}`,
    ASSIGN: (id: string) => `/admin/support-tickets/${id}/assign`,
    STATUS: (id: string) => `/admin/support-tickets/${id}/status`,
    MESSAGES: (id: string) => `/admin/support-tickets/${id}/messages`,
    RESOLUTIONS: (id: string) => `/admin/support-tickets/${id}/resolutions`,
    CATEGORY: (id: string) => `/admin/support-tickets/${id}/category`,
  },
  ADMIN_NOTIFICATIONS: {
    BROADCAST: "/admin/notifications/broadcast",
    HISTORY: "/admin/notifications",
  },
  SUPPORT_TICKETS: {
    BASE: "/support-tickets",
    MINE: "/support-tickets/mine",
    DETAIL: (id: string) => `/support-tickets/${id}`,
    MESSAGES: (id: string) => `/support-tickets/${id}/messages`,
    SURVEY: (id: string) => `/support-tickets/${id}/survey`,
    ATTACHMENTS: (id: string) => `/support-tickets/${id}/attachments`,
  },
  // ─── Incident ──────────────────────────────────────────────────────────────
  INCIDENTS: {
    BASE: "/incidents",
    MINE: "/incidents/mine",
    DETAIL: (id: string) => `/incidents/${id}`,
    EVIDENCES: "/incidents/evidences", // upload trước khi tạo (không có :id)
    WITHDRAW: (id: string) => `/incidents/${id}/withdraw`,
  },
  TASKER_INCIDENTS: {
    MINE: "/tasker/incidents/mine",
    DETAIL: (id: string) => `/tasker/incidents/${id}`,
    EVIDENCES: "/tasker/incidents/evidences",
    STATEMENTS: (id: string) => `/tasker/incidents/${id}/statements`,
  },
  ADMIN_INCIDENTS: {
    BASE: "/admin/incidents",
    CONFIG: "/admin/incidents/config",
    DETAIL: (id: string) => `/admin/incidents/${id}`,
    ACCEPT: (id: string) => `/admin/incidents/${id}/accept`,
    VERIFY: (id: string) => `/admin/incidents/${id}/items/verify`,
    DECIDE: (id: string) => `/admin/incidents/${id}/decide`,
    APPROVE_COMPENSATION: (id: string) => `/admin/incidents/${id}/approve-compensation`,
    COMPENSATE: (id: string) => `/admin/incidents/${id}/compensate`,
    UNLOCK_REPORTER: (id: string) => `/admin/incidents/${id}/unlock-reporter`,
    FROM_TICKET: (ticketId: string) => `/admin/incidents/from-ticket/${ticketId}`,
    HOUSEKEEPING: "/admin/incidents/run-housekeeping",
  },
};
