export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    REFRESH: "/auth/refresh",
    ME: "/auth/me",
    PROFILE: "/auth/profile",
    LOGOUT: "/auth/logout",
    VERIFY_EMAIL: "/auth/verify-email",
    RESEND_VERIFICATION_EMAIL: "/auth/resend-verification-email",
    VERIFY_LOGIN_OTP: "/auth/verify-login-otp",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
  },
  USERS: {
    BASE: "/users",
    PROFILE: "/users/profile",
  },
  CUSTOMER: {
    PROFILE: "/customer/profile/me",
    ADDRESSES: "/customer/addresses",
    ADDRESS: (id: string) => `/customer/addresses/${id}`,
    DEFAULT_ADDRESS: (id: string) => `/customer/addresses/${id}/default`,
  },
  TASKERS: {
    BASE: "/taskers",
    VERIFY: "/taskers/verify",
    UPDATE_PRESENCE: "/tasker/me/presence",
  },
  SERVICES: {
    BASE: "/services",
    CATEGORIES: "/services/categories",
  },
  PUBLIC: {
    CATEGORIES: "/public/categories",
    SERVICES: "/public/services",
  },
  SUB_SERVICES: {
    LIST: "/admin/sub-services",
    DETAIL: (id: string) => `/admin/sub-services/${id}`,
  },
  BOOKING: {
    // Customer APIs
    QUOTE: "/booking/quote",
    CREATE: "/booking",
    MY_ACTIVE: "/booking/my-booking",
    MY_LIST: "/booking/my-bookings",
    DETAIL: (id: string) => `/booking/${id}`,
    MOCK_PAY: (id: string) => `/booking/${id}/mock-pay`,
    CANCEL: (id: string) => `/booking/customer/${id}/cancel`,
    UPDATE_SCHEDULE: (id: string) => `/booking/${id}/schedule-address`,
    // Tasker APIs
    TASKER_ACTIVE: "/booking/tasker/active/current",
    TASKER_POSTED_LIST: "/booking/tasker/posted",
    TASKER_POSTED_DETAIL: (id: string) => `/booking/tasker/posted/${id}`,
    TASKER_ACCEPT: (id: string) => `/booking/tasker/posted/${id}/accept`,
    TASKER_ASSIGNED: (id: string) => `/booking/tasker/${id}`,
    TASKER_ON_WAY: (id: string) => `/booking/tasker/${id}/on-the-way`,
    TASKER_CHECKIN: (id: string) => `/booking/tasker/${id}/check-in`,
    TASKER_START: (id: string) => `/booking/tasker/${id}/start`,
    TASKER_COMPLETE: (id: string) => `/booking/tasker/${id}/complete`,
  },
  ADMIN_SUPPORT_TICKETS: {
    BASE: "/admin/support-tickets",
    CONFIG: "/admin/support-tickets/config",
    UNREAD_TOTAL: "/admin/support-tickets/unread-total",
    DETAIL: (id: string) => `/admin/support-tickets/${id}`,
    ASSIGN: (id: string) => `/admin/support-tickets/${id}/assign`,
    STATUS: (id: string) => `/admin/support-tickets/${id}/status`,
    MESSAGES: (id: string) => `/admin/support-tickets/${id}/messages`,
    INTERNAL_NOTES: (id: string) =>
      `/admin/support-tickets/${id}/internal-notes`,
    READ: (id: string) => `/admin/support-tickets/${id}/read`,
    ATTACHMENTS: (id: string) => `/admin/support-tickets/${id}/attachments`,
    RESOLUTIONS: (id: string) => `/admin/support-tickets/${id}/resolutions`,
    CATEGORY: (id: string) => `/admin/support-tickets/${id}/category`,
  },
  ADMIN_NOTIFICATIONS: {
    BROADCAST: "/admin/notifications/broadcast",
    HISTORY: "/admin/notifications",
  },
  NOTIFICATIONS: {
    LIST: "/notifications",
    UNREAD_COUNT: "/notifications/unread-count",
    READ_ALL: "/notifications/read-all",
    READ_ONE: (id: string) => `/notifications/${id}/read`,
  },
  SUPPORT_TICKETS: {
    BASE: "/support-tickets",
    MINE: "/support-tickets/mine",
    UNREAD_TOTAL: "/support-tickets/unread-total",
    DETAIL: (id: string) => `/support-tickets/${id}`,
    MESSAGES: (id: string) => `/support-tickets/${id}/messages`,
    READ: (id: string) => `/support-tickets/${id}/read`,
    SURVEY: (id: string) => `/support-tickets/${id}/survey`,
    ATTACHMENTS: (id: string) => `/support-tickets/${id}/attachments`,
  },
  // ─── Incident ──────────────────────────────────────────────────────────────
  INCIDENTS: {
    BASE: "/incidents",
    MINE: "/incidents/mine",
    DETAIL: (id: string) => `/incidents/${id}`,
    EVIDENCES: "/incidents/evidences", // upload trước khi tạo (không có :id)
    WITHDRAW: (id: string) => `/incidents/${id}/withdraw`,
  },
  TASKER_INCIDENTS: {
    MINE: "/tasker/incidents/mine",
    DETAIL: (id: string) => `/tasker/incidents/${id}`,
    EVIDENCES: "/tasker/incidents/evidences",
    STATEMENTS: (id: string) => `/tasker/incidents/${id}/statements`,
  },
  ADMIN_INCIDENTS: {
    BASE: "/admin/incidents",
    CONFIG: "/admin/incidents/config",
    DETAIL: (id: string) => `/admin/incidents/${id}`,
    ACCEPT: (id: string) => `/admin/incidents/${id}/accept`,
    VERIFY: (id: string) => `/admin/incidents/${id}/items/verify`,
    DECIDE: (id: string) => `/admin/incidents/${id}/decide`,
    APPROVE_COMPENSATION: (id: string) =>
      `/admin/incidents/${id}/approve-compensation`,
    COMPENSATE: (id: string) => `/admin/incidents/${id}/compensate`,
    UNLOCK_REPORTER: (id: string) => `/admin/incidents/${id}/unlock-reporter`,
    FROM_TICKET: (ticketId: string) =>
      `/admin/incidents/from-ticket/${ticketId}`,
    HOUSEKEEPING: "/admin/incidents/run-housekeeping",
  },
  ADMIN_SERVICES: {
    BASE: "/admin/sub-services",
    DETAIL: (id: string) => `/admin/sub-services/${id}`,
    BOOKINGS: (id: string) => `/admin/sub-services/${id}/bookings`,
    TASKERS: (id: string) => `/admin/sub-services/${id}/taskers`,
  },
  ADMIN_SERVICE_PACKAGES: {
    BASE: "/admin/service-packages",
    DETAIL: (id: string) => `/admin/service-packages/${id}`,
    ANALYTICS: (id: string) => `/admin/service-packages/${id}/analytics`,
    SUB_SERVICES: (id: string) => `/admin/service-packages/${id}/sub-services`,
    REMOVE_SUB_SERVICE: (id: string, subServiceId: string) =>
      `/admin/service-packages/${id}/sub-services/${subServiceId}`,
  },
  ADMIN_BOOKINGS: {
    BASE: "/admin/bookings",
    DETAIL: (id: string) => `/admin/bookings/${id}`,
    AVAILABLE_TASKERS: (id: string) =>
      `/admin/bookings/${id}/available-taskers`,
    ASSIGN_TASKER: (id: string) => `/admin/bookings/${id}/tasker`,
    STATUS: (id: string) => `/admin/bookings/${id}/status`,
    CANCEL: (id: string) => `/admin/bookings/${id}/cancel`,
    EXPIRE_OVERDUE: "/admin/bookings/expire-overdue",
    ACTIVE_TASKERS: "/admin/bookings/taskers/active",
  },
  ADMIN_CUSTOMERS: {
    BASE: "/admin/customers",
    DETAIL: (id: string) => `/admin/customers/${id}`,
    BOOKINGS: (id: string) => `/admin/customers/${id}/bookings`,
    STATUS: (id: string) => `/admin/customers/${id}/status`,
  },
  ADMIN_POLICIES: {
    BASE: "/policy",
    DETAIL: (id: string) => `/policy/${id}`,
    PACKAGES_BY_POLICY: (id: string) => `/policy/${id}/packages`,
    SEED: "/policy/seed",
    DEFAULTS: "/policy/defaults",
    PUBLIC_ALL: "/policy/public/all",
    PUBLIC_BY_SLUG: (slug: string) => `/policy/public/by-slug/${slug}`,
    // Package assignment
    PACKAGE_POLICIES: (pkgId: string) => `/policy/packages/${pkgId}`,
    ASSIGN_TO_PACKAGE: (pkgId: string) => `/policy/packages/${pkgId}/assign`,
    REMOVE_FROM_PACKAGE: (pkgId: string, policyId: string) => `/policy/packages/${pkgId}/policies/${policyId}`,
    APPLY_DEFAULTS: (pkgId: string) => `/policy/packages/${pkgId}/apply-defaults`,
  },
  ADMIN_PRICING: {
    CONFIGS: "/admin/pricing/configs",
    CONFIG_DETAIL: (id: string) => `/admin/pricing/configs/${id}`,
    PEAK_DAYS: "/admin/pricing/peak-days",
    PEAK_DAY_DETAIL: (id: string) => `/admin/pricing/peak-days/${id}`,
  },
  ADMIN_SETTINGS: {
    BASE: "/admin/settings",
  },
};
