export const ROUTES = {
  HOME: "/",
  AUTH: {
    LOGIN: "/login",
    LOGIN_ADMIN: "/login-admin",
    LOGIN_TASKER: "/login-tasker",
    REGISTER: "/register",
    FORGOT_PASSWORD: "/forgot-password",
    VERIFY_EMAIL: "/verify-email",
    OTP_VERIFY: "/otp-verify",
  },
  CUSTOMER: {
    DASHBOARD: "/customer",
    PROFILE: "/customer/profile",
    ADDRESSES: "/customer/addresses",
    BOOKING_WIZARD: "/customer/booking",
    HISTORY: "/customer/history",
    WALLET: "/customer/wallet",
    CATALOG: "/customer/catalog",
    INCIDENT: "/customer/incident",
    NOTIFICATIONS: "/customer/notifications",
    SUPPORT_TICKETS: "/customer/support-tickets",
    SUPPORT_TICKET_DETAIL: (id: string) => `/customer/support-tickets/${id}`,
  },
  TASKER: {
    DASHBOARD: "/tasker",
    PROFILE: "/tasker/profile",
    SCHEDULE: "/tasker/schedule",
    SETTINGS: "/tasker/settings",
    ONBOARDING: "/tasker/onboarding",
    SUPPORT_TICKETS: "/tasker/support-tickets",
    SUPPORT_TICKET_DETAIL: (id: string) => `/tasker/support-tickets/${id}`,
  },
  ADMIN: {
    DASHBOARD: "/admin",
    CUSTOMERS: "/admin/customers",
    TASKERS: "/admin/taskers",
    SERVICES: "/admin/services",
    BOOKINGS: "/admin/bookings",
    REPORTS: "/admin/reports",
    SETTINGS: {
      BASE: "/admin/settings",
      PEAK_DAYS: "/admin/settings/peak-days",
    },
  },
} as const;
