export const ROUTES = {
  HOME: "/",
  AUTH: {
    LOGIN: "/login",
    LOGIN_ADMIN: "/login-admin",
    LOGIN_TASKER: "/login-tasker",
    REGISTER: "/register",
    FORGOT_PASSWORD: "/forgot-password",
    VERIFY_EMAIL: "/verify-email",
    OTP_VERIFY: "/otp-verify",
  },
  CUSTOMER: {
    DASHBOARD: "/customer",
    PROFILE: "/customer/profile",
    ADDRESSES: "/customer/addresses",
    BOOKING_WIZARD: "/customer/booking",
    HISTORY: "/customer/history",
    WALLET: "/customer/wallet",
    CATALOG: "/customer/catalog",
    INCIDENT: "/customer/incident",
    INCIDENT_DETAIL: (id: string) => `/customer/incident/${id}`,
    INCIDENT_REPORT: "/customer/incident/report",
    NOTIFICATIONS: "/customer/notifications",
    SUPPORT_TICKETS: "/customer/support-tickets",
    SUPPORT_TICKET_DETAIL: (id: string) => `/customer/support-tickets/${id}`,
  },
  TASKER: {
    DASHBOARD: "/tasker",
    PROFILE: "/tasker/profile",
    SCHEDULE: "/tasker/schedule",
    SETTINGS: "/tasker/settings",
    ONBOARDING: "/tasker/onboarding",
    SUPPORT_TICKETS: "/tasker/support-tickets",
    SUPPORT_TICKET_DETAIL: (id: string) => `/tasker/support-tickets/${id}`,
    INCIDENTS: "/tasker/incidents",
    INCIDENT_DETAIL: (id: string) => `/tasker/incidents/${id}`,
  },
  ADMIN: {
    DASHBOARD: "/admin",
    ACTIVITY: "/admin/activity",
    SERVICE_PACKAGES: "/admin/service-packages",
    REPORTS: {
      BASE: "/admin/reports",
      TASKERS: "/admin/reports/taskers",
      BOOKINGS: "/admin/reports/bookings",
    },
    BOOKINGS: "/admin/bookings",
    SERVICES: {
      BASE: "/admin/services",
      CREATE: "/admin/services/create-package",
      SUB_SERVICES: "/admin/services/sub-services",
    },
    POLICIES: {
      BASE: "/admin/policies",
      DEFAULTS: "/admin/policies/defaults",
    },
    CUSTOMERS: {
      BASE: "/admin/customers",
      REVIEWS: "/admin/reviews",
    },
    TASKERS: {
      BASE: "/admin/taskers",
      VERIFICATION: "/admin/taskers/verification",
      SCHEDULE: "/admin/taskers/schedule",
      PAYROLL: "/admin/taskers/payroll",
    },
    TRACKING: {
      BASE: "/admin/tracking",
      ROUTES: "/admin/tracking/routes",
    },
    NOTIFICATIONS: "/admin/notifications",
    FINANCES: {
      BASE: "/admin/finances",
      WITHDRAWALS: "/admin/withdrawals",
      WALLETS: "/admin/wallets",
    },
    VOUCHERS: {
      BASE: "/admin/vouchers",
      CREATE: "/admin/vouchers/create",
    },
    SUPPORT_TICKETS: {
      BASE: "/admin/support-tickets",
    },
    SETTINGS: {
      BASE: "/admin/settings",
      PEAK_DAYS: "/admin/settings/peak-days",
      ROLES: "/admin/roles",
    },
  },
} as const;

