export enum BookingCheckinReviewStatus {
  NOT_REQUIRED = 'NOT_REQUIRED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  NOT_VERIFIABLE = 'NOT_VERIFIABLE',
}
