export enum BookingCheckinVerificationSource {
  GPS = 'GPS',
  GPS_WITH_PROOF = 'GPS_WITH_PROOF',
  GPS_LOW_ACCURACY_WITH_PROOF = 'GPS_LOW_ACCURACY_WITH_PROOF',
  NO_GPS_WITH_PROOF = 'NO_GPS_WITH_PROOF',
  TARGET_MISSING_WITH_PROOF = 'TARGET_MISSING_WITH_PROOF',
  ADMIN_OVERRIDE = 'ADMIN_OVERRIDE',
}
