export enum BookingStatus {
  POSTED = 'POSTED',
  PENDING_CUSTOMER_CONFIRMATION = 'PENDING_CUSTOMER_CONFIRMATION',
  CONFIRMED = 'CONFIRMED',
  TASKER_ON_THE_WAY = 'TASKER_ON_THE_WAY',
  CHECKED_IN = 'CHECKED_IN',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}
