export enum CancelledBy {
  CUSTOMER = 'CUSTOMER',
  TASKER = 'TASKER',
  SYSTEM = 'SYSTEM',
  ADMIN = 'ADMIN',
  CUSTOMER_DECLINED = 'CUSTOMER_DECLINED',
  SYSTEM_TIMEOUT = 'SYSTEM_TIMEOUT',
  CUSTOMER_ABSENT = 'CUSTOMER_ABSENT',
}
