export enum IncidentEvidencePurpose {
  DAMAGE_PHOTO = 'DAMAGE_PHOTO',
  BEFORE_PHOTO = 'BEFORE_PHOTO',
  PURCHASE_RECEIPT = 'PURCHASE_RECEIPT',
  REPAIR_QUOTE = 'REPAIR_QUOTE',
  TASKER_STATEMENT = 'TASKER_STATEMENT',
  DECISION_RESPONSE = 'DECISION_RESPONSE',
  // P0.4 — ảnh chuyển khoản thủ công khi quỹ SYSTEM không đủ (ADMIN_ONLY).
  COMPENSATION_TRANSFER_PROOF = 'COMPENSATION_TRANSFER_PROOF',
  OTHER = 'OTHER',
}
