export enum IncidentDecisionStatus {
  NONE = 'NONE',
  DRAFT = 'DRAFT',
  PENDING_TASKER_RESPONSE = 'PENDING_TASKER_RESPONSE',
  PENDING_ADMIN_APPROVAL = 'PENDING_ADMIN_APPROVAL',
  FINAL = 'FINAL',
}
