export enum NotificationType {
  BOOKING_NEW_AVAILABLE = 'BOOKING_NEW_AVAILABLE',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  TASKER_ON_THE_WAY = 'TASKER_ON_THE_WAY',
  BOOKING_COMPLETED = 'BOOKING_COMPLETED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  INCIDENT_UPDATE = 'INCIDENT_UPDATE',
  SUPPORT_REPLY = 'SUPPORT_REPLY',
  PROMOTION = 'PROMOTION',
  SYSTEM = 'SYSTEM',
  BOOKING_PENDING_CONFIRMATION = 'BOOKING_PENDING_CONFIRMATION',
  BOOKING_SURCHARGE_PENDING = 'BOOKING_SURCHARGE_PENDING',
}
S