export enum TaskerDepositTransactionType {
  CASH_COMMISSION_DEDUCT = 'CASH_COMMISSION_DEDUCT',
  INCIDENT_COMPENSATION_DEDUCT = 'INCIDENT_COMPENSATION_DEDUCT',
  TOP_UP = 'TOP_UP',
  TERMINATION_REFUND = 'TERMINATION_REFUND',
}
