export enum TicketCategory {
  SERVICE_QUALITY = 'SERVICE_QUALITY',
  TASKER_BEHAVIOR = 'TASKER_BEHAVIOR',
  SCHEDULING = 'SCHEDULING',
  PROPERTY_DAMAGE = 'PROPERTY_DAMAGE',
  PAYMENT_BILLING = 'PAYMENT_BILLING',
  ACCOUNT_TECHNICAL = 'ACCOUNT_TECHNICAL',
  APPEAL = 'APPEAL',
  OTHER = 'OTHER',
}
