export const colors = {
  primary: "#006b32",
  primaryContainer: "#008740",
  primaryFixed: "#78fc9c",
  secondary: "#855300",
  secondaryContainer: "#fea619",
  surface: "#f8f9ff",
  surfaceLow: "#eff4ff",
  surfaceContainer: "#e6eeff",
  surfaceContainerHighest: "#d9e3f6",
  surfaceContainerHigh: "#dee9fc",
  surfaceDim: "#d0dbed",
  surfaceBright: "#f8f9ff",
  inverseSurface: "#27313f",
  onSurface: "#121c2a",
  onSurfaceVariant: "#3d4a3e",
  onPrimary: "#ffffff",
  onPrimaryFixed: "#00210b",
  onPrimaryFixedVariant: "#005225",
  onSecondary: "#ffffff",
  onSecondaryContainer: "#684000",
  onTertiary: "#ffffff",
  tertiary: "#a72e4a",
  tertiaryContainer: "#c84761",
  tertiaryFixed: "#ffd9dd",
  tertiaryFixedDim: "#ffb2bb",
  outline: "#6d7b6d",
  outlineVariant: "#bccabb",
  error: "#ba1a1a",
  errorContainer: "#ffdad6",
} as const

export type Colors = typeof colors