export const INCIDENT_HOUSEKEEPING_INTERVAL_MS =
  'INCIDENT_HOUSEKEEPING_INTERVAL_MS';

export const IC_CONFIG_KEYS = {
  REPORT_WINDOW_HOURS: 'INCIDENT_REPORT_WINDOW_HOURS',
  REPORT_WINDOW_SEVERE_HOURS: 'INCIDENT_REPORT_WINDOW_SEVERE_HOURS',
  SEVERE_CRITERIA: 'INCIDENT_SEVERE_CRITERIA',
  CLAIM_MAX_AMOUNT: 'INCIDENT_CLAIM_MAX_AMOUNT',
  EVIDENCE_REQUIRED_THRESHOLD: 'INCIDENT_EVIDENCE_REQUIRED_THRESHOLD',
  DUAL_APPROVAL_THRESHOLD: 'INCIDENT_DUAL_APPROVAL_THRESHOLD',
  COMPENSATION_POLICY_CAP: 'INCIDENT_COMPENSATION_POLICY_CAP',
  COOLING_PERIOD_HOURS: 'INCIDENT_COOLING_PERIOD_HOURS',
  DEPOSIT_TOPUP_GRACE_DAYS: 'INCIDENT_DEPOSIT_TOPUP_GRACE_DAYS',
  AUTOCLOSE_HOURS: 'INCIDENT_AUTOCLOSE_HOURS',
  REPORTED_EXPIRY_DAYS: 'INCIDENT_REPORTED_EXPIRY_DAYS',
  SLA_MATRIX: 'INCIDENT_SLA_MATRIX',
  FALSE_REPORT_STRIKES: 'INCIDENT_FALSE_REPORT_STRIKES',
} as const;

export const IC_DEFAULTS = {
  REPORT_WINDOW_HOURS: 48,
  REPORT_WINDOW_SEVERE_HOURS: 72,
  CLAIM_MAX_AMOUNT: 20_000_000,
  EVIDENCE_REQUIRED_THRESHOLD: 1_000_000,
  DUAL_APPROVAL_THRESHOLD: 2_000_000,
  COMPENSATION_POLICY_CAP: 10_000_000,
  COOLING_PERIOD_HOURS: 24,
  DEPOSIT_TOPUP_GRACE_DAYS: 7,
  AUTOCLOSE_HOURS: 48,
  REPORTED_EXPIRY_DAYS: 30,
  SEVERE_AMOUNT: 5_000_000,
  MAJOR_AMOUNT: 1_000_000,
};

export interface SevereCriteria {
  categories?: string[];
  severeAmount?: number;
  majorAmount?: number;
}
